kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:serviceaccount:default:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: market-place-mongodb
spec:
  selector:
    matchLabels:
      app: market-place-mongodb
  serviceName: "market-place-mongodb"
  replicas: 3
  template:
    metadata:
      labels:
        app: market-place-mongodb
        role: market-place-mongodb
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: market-place-mongodb
          image: mongo:4.2.1
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: market-place-mongodb
              mountPath: /data/db      
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=market-place-mongodb,environment=test"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: market-place-mongodb
      volumes:
        - name: market-place-mongodb
  volumeClaimTemplates:
    - metadata:
        name: market-place-mongodb        
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: market-place-mongodb
  labels:
    app: market-place-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: market-place-mongodb